import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import  { attributes, react as HomeContent }  from '@content/pages/home.md';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  let { hero_title, hero_description } = attributes;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <article>
          <h1>{hero_title}</h1>
          <HomeContent />
        </article>
        </div>
      </main>
    </>
  )
}
